[build-system]
requires = ["setuptools>=61.0.0", "wheel"]

[project]
name = "family"
version = "0.1.0"
description = "A simple family"
authors = [{name = "Henrik Finsberg", email = "henriknf@simula.no"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
